### ISSUE TITLE
[ISSUE] Can't play or download Baku world feed

### ISSUE THREAD

**Issue by LuckyRed93** [robvdpol/RaceControl#154] opened 2021-06-06 17:53 UTC
This error appeared when I tried to download the 2021 Azerbaijan Grand Prix World Feed Race file: 
![2021-06-06](https://user-images.githubusercontent.com/85454253/120934863-5f6f7700-c700-11eb-877d-d431d1f20298.png)

The log file says this:
2021-06-06 19:41:26.7241 ERROR A critical error occurred.
System.Exception: An error occurred while opening the stream URL (error code: -3).
   at RaceControl.Flyleaf.FlyleafMediaDownloader.<>c__DisplayClass12_0.<StartDownloadAsync>b__0() in D:\Projects\RaceControl\RaceControl\RaceControl\Flyleaf\FlyleafMediaDownloader.cs:line 51
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at RaceControl.ViewModels.DownloadDialogViewModel.StartDownloadAsync() in D:\Projects\RaceControl\RaceControl\RaceControl\ViewModels\DownloadDialogViewModel.cs:line 66
   at System.Threading.Tasks.TaskExtensions.Await(Task task, Action completedCallback, Action`1 errorCallback, Boolean configureAwait)

**Comment by robvdpol** [comment] 2021-06-06 17:58
I can reproduce this.

@SuRGeoNix do you know what error code -3 means when calling VideoDemuxer.Open()?

**Comment by LuckyRed93** [comment] 2021-06-06 19:09
And it's only the World Feed that isn't working, the other feeds worked fine.

**Comment by SuRGeoNix** [comment] 2021-06-06 20:03
@robvdpol Can't see much from the logs but it seems that ffmpeg doesn't like the URL that the application parses. Can you check the url itself... does it work with other players? (Might be a string related issue)

**Comment by henshinger555** [comment] 2021-06-06 20:09
World Feed Works if you open it up in VLC but not the default player. Also affects casting as well.

**Comment by robvdpol** [comment] 2021-06-07 06:52
> @robvdpol Can't see much from the logs but it seems that ffmpeg doesn't like the URL that the application parses. Can you check the url itself... does it work with other players? (Might be a string related issue)

Yeah, it works fine in VLC and MPV. You up for some Skyping sometime this week?

**Comment by LuckyRed93** [comment] 2021-06-07 12:28
I have an update: everything works now. I just clicked download and it is currently downloading. I also clicked on Watch with internal player and it works now too.

**Comment by haggis310** [comment] 2021-06-07 12:56
> I have an update: everything works now. I just clicked download and it is currently downloading. I also clicked on Watch with internal player and it works now too.

That's due to the URL changing.  Yesterday it was being served by f1prodlive, today it's being served by f1prodvod.

**Comment by robvdpol** [comment] 2021-06-07 13:03
That's interesting, will keep an eye on it.

**Comment by robvdpol** [comment] 2021-06-11 08:39
Closing this issue for now, will re-open if this occurs again.

**Closed by robvdpol** 2021-06-11 08:39 UTC
