### ISSUE TITLE
[BUG] Can't run version 2.6.1 because of missing .NET which I already have installed

### ISSUE THREAD

**Issue by kwiznix** [robvdpol/RaceControl#386] opened 2022-03-25 12:16 UTC
When using the newest version (2.6.1) in with msi file and standalone version i got the message that I should download a version of .NET which I already have installed. As you can see in the second screenshot, I only have the repair, remove and close option.

When I've downloaded my previous version (2.5.5) again, and that version starts without any problem.

![image](https://user-images.githubusercontent.com/25011006/160118952-a83fd873-b379-4095-9672-68d4cacdd8c2.png)
![image](https://user-images.githubusercontent.com/25011006/160119002-26c3cd82-cbd8-4c60-866c-cc1c069af660.png)

**Comment by robvdpol** [comment] 2022-03-25 12:42
Duplicate of #355

**Closed by robvdpol** 2022-03-25 12:42 UTC
Labels: bug
