### ISSUE TITLE
[FEATURE] Dark mode in the app

### ISSUE THREAD

**Issue by reacap** [robvdpol/RaceControl#98] opened 2021-04-29 21:51 UTC
I don't know how possible it is , but it would be great to have an option of a dark mode in the app. 
A lot of people watch the races late in the day and white app interface a bit blinding .
Cheers

**Comment by robvdpol** [comment] 2021-04-30 07:35
Duplicate of issue #31

**Closed by robvdpol** 2021-04-30 07:35 UTC
Labels: duplicate
