### ISSUE TITLE
[BUG] Live sessions do not work. Recorded ones do.

### ISSUE THREAD

**Issue by zflash** [robvdpol/RaceControl#428] opened 2022-04-22 08:02 UTC
**Describe the bug**
New race control plays everything great except the live sessions. Non of the players work and the internal player gives garbage

**To Reproduce**
Just start an live session and it doesn't work

**Desktop (please complete the following information):**
 - Windows 10 up2date
 - 64bit
 - 2.6.4

**F1TV account**
- Pro subscription, no vpn

**Additional context**
Already recorded sessions play just fine, the live sessions do not.

**Comment by adipillay** [comment] 2022-04-22 08:15
getting error message "An error occurred while retrieving the stream URL"

**Comment by Gerbildral** [comment] 2022-04-22 08:16
Looks like a DRM issue
![image](https://user-images.githubusercontent.com/29066252/164647189-29ada94c-8b12-41fe-bf92-cf5530870979.png)

**Comment by adipillay** [comment] 2022-04-22 08:27
I think the DRM issue is not been fixed, this is what I glen from the Reddit sub for F1TV

**Comment by BeanXOfficial** [comment] 2022-04-22 08:28
Hi, having the same over here. VPN on or off doesn't seem to matter.
![8703aa9463d6574be1a7b389b5be04a7](https://user-images.githubusercontent.com/98171726/164649683-c2f57a6b-0035-4157-9460-2022aff44fca.png)

**Comment by rmaclean-ee** [comment] 2022-04-22 09:00
Duplicate of [!413](https://github.com/robvdpol/RaceControl/issues/413)

**Comment by PostMalone** [comment] 2022-04-22 09:06
This is DRM. Developers are working on it but I'm not sure when it will be fixed (if ever?).

**Comment by robvdpol** [comment] 2022-04-22 09:09
Duplicate of #413

**Closed by robvdpol** 2022-04-22 09:09 UTC
Labels: bug
