### ISSUE TITLE
Unable to cast live stream to chromecast[BUG]

### ISSUE THREAD

**Issue by geintje** [robvdpol/RaceControl#148] opened 2021-06-05 08:20 UTC
Since Monaco GP every live feed I am trying to cast give's ' Load failed' error
When I use F1 media android app from phone to stream to my Chromecast, it works flawless.
Any other cast ( from youtube) works fine.
Which makes me believe the issue is in the RaceControl App not in my Chromecast/home network.
Things I tried : 
- Logout and login again with working credentials
- uninstall RaceControl
- install RaceControl from GitHub and from Microsoft Store

Issue remains, any live feed gives ' Load failed' error.

[RaceControl.log](https://github.com/robvdpol/RaceControl/files/6602216/RaceControl.log)

All pre-recorded streams work fine, no issues there,

**Comment by petermbode** [comment] 2021-06-05 11:48
exact same issue here

**Comment by Lineos** [comment] 2021-06-05 21:26
Same here!

**Comment by maxverstappen** [comment] 2021-06-06 07:37
Same here 
Work around playing via VLC  and rendering to chromecast. Is a good workaround

**Comment by robvdpol** [comment] 2021-06-06 11:57
Duplicate of issue #132

**Closed by robvdpol** 2021-06-06 11:57 UTC
Labels: bug, duplicate
