### ISSUE TITLE
[BUG] Expected Framework missing

### ISSUE THREAD

**Issue by mahejo** [robvdpol/RaceControl#392] opened 2022-03-26 13:28 UTC
**Describe the bug**
Since 2.6.+ I can't run the application. It keeps asking for Framework .Net 6; also after I have installed the framework.

**Desktop (please complete the following information):**
 - Windows 11 Pro
 - System type (64 bit)
 - Version (10.0.22000 Build 22000)

**F1TV account**
- Subscription type (Pro)
- Denmark

**Additional context**
To fix it I have to uninstall Race Control and use an older version.

**Comment by sidewinder94** [comment] 2022-03-26 15:22
Which exact version of the runtime have you tried installing ?

Theoretically, you'll need the [.NET Desktop Runtime 6](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer) (links to version 6.0.3, because it's a security update,and it's the x64 version)

I don't know which version of RaceControl is included in the MSI, so you might have to install the x86 version instead.

The whole list of downloads can be found here : https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by robvdpol** [comment] 2022-03-27 12:22
Duplicate of #355

**Closed by robvdpol** 2022-03-27 12:22 UTC
Labels: bug
