### ISSUE TITLE
[BUG] Unable to drag Windows when using the internal player

### ISSUE THREAD

**Issue by therealabradolf** [robvdpol/RaceControl#64] opened 2021-03-27 07:22 UTC
**Describe the bug**
Since the latest update i can't move the streaming windows anymore when using the internal player.
As a result, when having multiple concurrent streams they're just stacked on top of each other.

**To Reproduce**
1. Start a stream using the "Watch" button.
2. Try to move the window using the mouse instead of the "Arrows" at the bottom.

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - System type 64bit
 - Version 2.0.2

**F1TV account**
- Subscription type Pro
- Belgium
- Using VPN or proxy? No

**Comment by robvdpol** [comment] 2021-03-27 09:23
You have to drag bij clicking and holding the actual video, not the menu bar. Will clarify in the readme.

Duplicate of issue #42.

**Closed by robvdpol** 2021-03-27 09:23 UTC
Labels: bug
