### ISSUE TITLE
[BUG]Internal player not working when event is live

### ISSUE THREAD

**Issue by Ardjan-git** [robvdpol/RaceControl#82] opened 2021-04-16 13:24 UTC
**Describe the bug**
the intertnal player is does not load the stream when the event is live. MPV player live works without a problem.
the internal player works without a problem when the event is not live.

**To Reproduce**
1. Go to 'a event that is live'
2. Play stream 'world feed'
3. Press button 'watch'

**Expected behavior**

steam loads and plays normaly 

**Screenshots**
![image](https://user-images.githubusercontent.com/79168314/115030638-9925bd80-9ec7-11eb-8150-acc2f305006c.png)

**Desktop (please complete the following information):**
 - Windows 10 and pro
 - System type (64)
 - Version (2004)

**F1TV account**
- Subscription type (Pro)
- NL

**Comment by robvdpol** [comment] 2021-04-16 13:30
Duplicate of issue #81

**Closed by robvdpol** 2021-04-16 13:30 UTC
Labels: bug, duplicate
