### ISSUE TITLE
[FEATURE] Make video dialog movable

### ISSUE THREAD

**Issue by jdschuitemaker** [robvdpol/RaceControl#46] opened 2021-03-15 18:14 UTC
**Is your feature request related to a problem? Please describe.**
Currently I cannot move the video dialog. I have a dual monitor setup and would like to move the video window from my primary to my secondary monitor. The only I way I can do that now is by resizing/moving the right border of the dialog to the 2nd monitor, then do the same with the left border.

**Describe the solution you'd like**
I would like to be able to drag the video dialog by clicking and holding the title bar and then drag/drop the window to my 2nd screen

**Describe alternatives you've considered**
n/a

**Additional context**
The buttons for full screen and placing the video dialog in a corner is nice to order multiple dialogs, but cannot be used to move them to a 2nd monitor. I would still like to keep these buttons though!

**Comment by robvdpol** [comment] 2021-03-15 18:21
You have to click/drag the actual video to move the window. Lots of (new) users are apparently confused by this. The menu bar wasn't there in previous releases so it was obvious to click/drag the video. I tried to make the menu bar draggable but no luck so far with that.

Duplicate of issue #42, closing.

**Closed by robvdpol** 2021-03-15 18:21 UTC
Labels: enhancement
