### ISSUE TITLE
[BUG] live stream video corrupt

### ISSUE THREAD

**Issue by rvdeijk** [robvdpol/RaceControl#421] opened 2022-04-10 06:55 UTC
**Describe the bug**
All livestreams of todays race with race Control gave corrupt video

Play a stream with watch, but vlc and mpc did not work as well

![IMG_20220410_085122](https://user-images.githubusercontent.com/35557458/162606274-8da21989-a4bc-4583-a99b-647d6c9fde91.jpg)

 - Windows 10H2 64bit
 - race Control 2.6.4

**F1TV account**
- Pro
- Netherlands

I had no issues with the previous race and version 2.6.3
Also when I playback a recording like the qualification it plays fine with 2.6.4. not sure why live stream suddenly does not work

**Comment by malles** [comment] 2022-04-10 06:56
That is #413 I assume, known problem with DRM.

**Comment by Spexxel** [comment] 2022-04-10 08:18
Should have been fixed in the latest release.
Did you follow the "IMPORTANT NOTE: Make sure to install the Microsoft Edge WebView2 Runtime on your system!"?
If so, try logging out and in

**Comment by Spexxel** [comment] 2022-04-10 08:53
Interesting. The replay of the race also wasnt working. But now about an hour later it is working..

**Comment by robvdpol** [comment] 2022-04-10 09:33
Duplicate of #413

**Closed by robvdpol** 2022-04-10 09:33 UTC
Labels: bug
