### ISSUE TITLE
[BUG] Cannot login get "system exception error"

### ISSUE THREAD

**Issue by chrcoluk** [robvdpol/RaceControl#72] opened 2021-03-28 17:26 UTC
**Describe the bug**
When I clock the login button in bottom of login window it says system exception error.

**To Reproduce**
1 - Install latest version racecontrol, for user only in installer option.
2 - Load the app
3 - Put in credentials and click login

**Expected behavior**
I expect the app would work after login?

**Desktop (please complete the following information):**
Windows 10 1809 LTSC
64 Bit
2.0.2

**F1TV account**
Pro
Romania
Using NordVPN Desktop client

If requested will supply screenshot.

**Comment by robvdpol** [comment] 2021-03-28 18:59
Duplicate of issue #62. Please read my response there.

**Closed by robvdpol** 2021-03-28 18:59 UTC
Labels: bug
