### ISSUE TITLE
Load fail 

### ISSUE THREAD

**Issue by gerritjm** [robvdpol/RaceControl#132] opened 2021-05-20 10:07 UTC
**Describe the bug**
Just installed latest version. After selecting my chromecast device and select [Cast] from the World Feed Channel, systems reports an error 'Load fail'

Television is showing the cast symbol, so it did get some sort of message from Race Control. 

![Screenshot_1](https://user-images.githubusercontent.com/84504573/118960628-c7ce0280-b963-11eb-9a14-09b94323cc45.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/84504573/118960646-cd2b4d00-b963-11eb-96de-b8df2de78f38.jpg)

It all was working perfect before the software update

**Comment by gerritjm** [comment] 2021-05-20 10:09
System = WIN 10 Pro, 20H2 19042.985

**Comment by DallieNL** [comment] 2021-05-20 10:31
Same issue here. W10 and Chromecast Ultra 2020. Installed the app today so no sure if it ever worked with my configuration. The log file is empty. 

On a side note, the folder for the log file was not created during install, needed to create it manually before app could create the file itself.

**Comment by gerritjm** [comment] 2021-05-20 10:31
Addition info and research: 
Casting works fine with  Spanish Grand prix replay. 

For the monaco F2 practise replay it finds the audio channel, briefly shows the F1 logo on my TV and then shows a blue casting symbol. No error messages. See 1st screen print. 

For current monaco F1 practice it errs before finding the audio channel. See 2nd screenshot. 

![Screenshot_3](https://user-images.githubusercontent.com/84504573/118963986-53955e00-b967-11eb-985b-42f11d91741a.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/84504573/118964006-585a1200-b967-11eb-9336-41aca2648305.jpg)

**Comment by gerritjm** [comment] 2021-05-20 10:38
> Same issue here. W10 and Chromecast Ultra 2020. Installed the app today so no sure if it ever worked with my configuration. The log file is empty.
> 
> On a side note, the folder for the log file was not created during install, needed to create it manually before app could create the file itself.

Did you try replaying Spanish GP? Those work and cast fine!

**Comment by DallieNL** [comment] 2021-05-20 11:40
Just checked, indeed no issues casting the Spanish race. For now only
Monaco seems affected. I had the same issue with the F2 practice as well
btw.

**Comment by djbarney** [comment] 2021-05-20 13:01
same issue here for me

**Comment by thomaskirz** [comment] 2021-05-20 13:04
Same for me.

**Comment by robvdpol** [comment] 2021-05-20 13:29
There's not much I can do about this, it's the Chromecast that's incompatible with some of the streams for some reason.

**Comment by djbarney** [comment] 2021-05-20 13:32
if it helps, the f1tv android app does stream correctly, even though that's usually less stable than race control via pc.

**Comment by cmcavoy** [comment] 2021-05-20 13:56
> There's not much I can do about this, it's the Chromecast that's incompatible with some of the streams for some reason.

I was able to stream from Chrome. Opened FP1 replay and FP2 live stream in the F1TV web app, then used the Chromecast button in the playback window.

**Comment by gerritjm** [comment] 2021-05-20 14:35
> > There's not much I can do about this, it's the Chromecast that's incompatible with some of the streams for some reason.
> 
> I was able to stream from Chrome. Opened FP1 replay and FP2 live stream in the F1TV web app, then used the Chromecast button in the playback window. I wasn't able to stream from Race Control, same issue as the OP.
> 
> Also - more than happy to test any fixes, I have a Chromecast device.

Same here, casted FP2 via F1TV webapp. Remarkably stable for a change....

**Comment by gerritjm** [comment] 2021-05-21 06:49
Update: Both FP1 and FP2 can be replayed and casted from Race Control. No clue as to why this wasn't working yesterday.

**Comment by djbarney** [comment] 2021-05-22 10:07
today the same thing with free practice 3, load failed message while trying to cast it. plays perfectly fine otherwise, so i'll watch it on pc :) hope the attached log has some useful information for you
[RaceControl.log](https://github.com/robvdpol/RaceControl/files/6526199/RaceControl.log)

**Comment by reflexx666** [comment] 2021-05-22 10:09
Same issue here, live casting is not possible anymore while it has been last week. I can cast replays but just no livestreams.

**Comment by geintje** [comment] 2021-05-22 11:54
> Update: Both FP1 and FP2 can be replayed and casted from Race Control. 
> However, casting a live stream generates the Load Fail err.

Same result today for me.
From RC 2.3.0 I could cast FP1 and FP2.
FP3 gave 'Load Fail' err . After FP3 was done I kept trying , still ' load Fail' err.

**Comment by woldhek** [comment] 2021-05-22 13:18
Just here to confirm i also have the same issue with chromecast.

**Comment by Lineos** [comment] 2021-05-23 12:28
Same here. I now cast from the F1 app on my iPhone. No problems there.

**Comment by mpg917** [comment] 2021-05-24 15:33
Same problems here - "Load Fail" - log attached.  Looks like some parsing problem?

But cast from Android F1TV app to Chromecast was super stable - zero problems this time.

[RaceControl.log](https://github.com/robvdpol/RaceControl/files/6533427/RaceControl.log)

**Comment by geintje** [comment] 2021-06-04 12:08
Still Load issue with FP2 casting..
I uninstalled old F1 RC program and installed latest 2.3.1.
FP2 is now live, but casting gives 'Load Failed' error.

From my phone , android app 'F1 media android' cast is flawless.
Make me believe the issue is in the Race Control programm, not in the chromecast of mine.

**Comment by maxverstappen** [comment] 2021-06-06 07:43
Work around. Cast to VLC and render to chromecast

**Comment by bartdevriendt** [comment] 2021-06-06 11:25
I digged deeper into this issue.

When testing I saw that after trying to start a live session chromecast returns an error:

{"requestId":1576829659,"type":"LOAD_FAILED","detailedErrorCode":311,"itemId":1}

I picked the url of the livestream and tried to validate it on some websites but these all say there is an issue with the access control origin header.  Then I validated this:

Non-live session:

https://f1prodvod.akamaized.net/out/v1/4e07b0a85fe04f879b4c9064a2396ab0/33957307c5b848a6bea693bb400a7166/e4d49ef8077f4032a097e2b0c8a962bb/index.m3u8?hdnea=st=1622973837~exp=1622974137~acl=/out/v1/4e07b0a85fe04f879b4c9064a2396ab0/*~hmac=f3aedec5b7b3.....

Headers returned:

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.18.0
< Content-Length: 5572
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,POST,OPTIONS
< Access-Control-Allow-Headers: origin,range,hdntl,hdnts
< Access-Control-Expose-Headers: Server,range,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 86400
< Akamai-Mon-Iucid-Del: 1162046
< X-MediaPackage-Request-Id: Root=1-60bba47e-20fff56161c981a41486e523
< Expires: Sun, 06 Jun 2021 11:18:21 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Sun, 06 Jun 2021 11:18:21 GMT
< Connection: keep-alive
< Content-Type: application/vnd.apple.mpegurl
< Content-Type: application/x-mpegURL

Live session:

https://f1prodlive.akamaized.net/out/v1/ba5356de41ba4032b3183201a74c0bd8/index.m3u8?hdnea=st=1622974133~exp=1622974433~acl=/out/v1/ba5356de41ba4032b3183201a74c0bd8/*~hmac=047bac2e2....

Headers returned:

< HTTP/1.1 200 OK
< Server: nginx/1.18.0
< X-MediaPackage-Request-Id: Root=1-60bcaf54-088bd08e5127c8a3152a7c47
< Expires: Sun, 06 Jun 2021 11:19:48 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Sun, 06 Jun 2021 11:19:48 GMT
< Connection: keep-alive
< Akamai-Mon-Iucid-Del: 1135586
< Content-Type: application/x-mpegURL
< Access-Control-Max-Age: 86400
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Server,range,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC
< Access-Control-Allow-Headers: origin,range,hdntl,hdnts
< Access-Control-Allow-Methods: GET,POST,OPTIONS
< Content-Length: 2132

So it seems google chromecast is checking the "Access-Control-Allow-Origin" header to start streaming, and this header is missing on the live sessions.  This issue can only be fixed by F1 itself.

I'm wondering though if it would be possible to send another url as the browser is doing.

**Comment by robvdpol** [comment] 2021-06-06 18:43
@bartdevriendt Thanks for your investigation. Yes, it would be nice if we could somehow check how the F1TV website handles Chromecasting.

**Comment by geintje** [comment] 2021-06-09 06:52
@bartdevriendt  Thank you for a deeper dive into this issue.
Both F1 media stream from their website ( live and recorded) as the android F1 app works fine casting to chrome cast.
Beside looking how the F1 media webside send the URL, perhaps there is a way to send the stream as the android F1 app is doing.
Just an idea ..

**Comment by JohnBruil** [comment] 2021-06-18 15:29
also the fp1 and 2 from the French GP today are giving the load failed error. Any sight on some sort of solution?

**Comment by geintje** [comment] 2021-06-18 18:08
> also the fp1 and 2 from the French GP today are giving the load failed error. Any sight on some sort of solution?
Even the 'replay' give 'load fail'.
Since Monaco GP , Race control program is unusable for me.
kudo's for trying, but no cigar.
For casting I rely on the android F1 App, which proved to be stable.

**Comment by bartdevriendt** [comment] 2021-06-19 10:40
I don't get it.  All I can see is that the browser is sending the same url.   I have no clue why it works for the browser but not with C# cast clients...

**Comment by geintje** [comment] 2021-06-19 11:47
Perhaps C# send more or less than the browser, beside the same URL ? Which makes the Chromecast rejects the stream ?

**Comment by bartdevriendt** [comment] 2021-06-19 13:42
I tried to do the same thing with python and it gives the same error.

**Comment by geintje** [comment] 2021-06-20 09:14
Let see if I understand this.
The F1 website , when casting is sending an URL to the chrome cast.
You managed to capture that URL, but when C# or Python is sending the same URL to a Chromecast it results in an error.
Is there a way to filter the URL, remove what is causing the error, or add a piece of text to the URL so chromecast thinks it is authenticated ?
My programming skills are limited , since I am more of a hardware oriented guy,

**Comment by bartdevriendt** [comment] 2021-06-20 10:52
Finally found a solution for this.  Opened a PR to approve and merge !

**Comment by JohnBruil** [comment] 2021-06-20 10:56
@bartdevriendt : that's great news!  Thx a lot!

**Comment by robvdpol** [comment] 2021-06-20 11:39
Thanks, I'll try to merge and create a pre-release before the race.

**Comment by robvdpol** [comment] 2021-06-20 12:10
Hotfix has been released as a pre-release, you can get it [here](https://github.com/robvdpol/RaceControl/releases/tag/2.3.2).

Thanks @bartdevriendt for your work!

**Closed by robvdpol** 2021-06-20 12:10 UTC
Labels: bug

**Comment by Lundelll** [comment] 2021-06-21 09:01
> Hotfix has been released as a pre-release, you can get it [here](https://github.com/robvdpol/RaceControl/releases/tag/2.3.2).
> 
> Thanks @bartdevriendt for your work!

Can confirm that this fix solved my issue. Thank you!
