### ISSUE TITLE
No sound when changing audio

### ISSUE THREAD

**Issue by jorgegambini** [robvdpol/RaceControl#38] opened 2021-03-12 19:36 UTC
The video starts correctly with audio in English, but when changing to another language (for example Spanish) it runs out of sound. Even if I go back to English audio, it still has no sound.

 - Windows 10 Pro
 - 64 bit
 - 20H2

- F1TV Pro
- Argentina
- No VPN

**Comment by robvdpol** [comment] 2021-03-13 10:46
It's a VLC bug unfortunately, so I can't do anything about it. I've been in contact with them about this issue, so hopefully it will be resolved in a future VLC release.

If you want to watch in a different language I would recommend using MPV, it works flawlessly.

**Comment by jorgegambini** [comment] 2021-03-13 11:45
Thank you very much, with MPV the audio track change works perfectly. The problem happens with VLC and with the Internal Player. Greetings.

**Comment by robvdpol** [comment] 2021-03-13 13:29
Duplicate of issue #5, so closing this one.

**Closed by robvdpol** 2021-03-13 13:29 UTC
Labels: duplicate
