### ISSUE TITLE
[BUG] Program freezing and crashing when trying to scrub through driver on-board

### ISSUE THREAD

**Issue by anarchomushroom** [robvdpol/RaceControl#185] opened 2021-07-18 19:14 UTC
**Describe the bug**
When watching the race VOD, with multiple videos (in this case, 4), whenever I tried to scrub through the vide of the driver on board, or sync other videos up with the main feed, or use the toggle pause on all players, the program freezes and generates an error message saying "Thread abort not supported on this platform". Often the driver on board video just freezes and does not play.

**To Reproduce**
1. Go to 'British Grand Prix 2021'
2. Play stream 'World Feed', 'Daniel Ricciardo', 'Live Timing', and 'Driver Tracker'
3. Press button 'play/pause all players' OR sync OR scrub through driver on board
4. See error: "Thread abort not supported on this platform"

**Expected behavior**
The videos should sync up and then play/pause all at once so that everything is synced, but only three streams actually sync, whilst the driver on board does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/52526629/126079441-e19313ae-dbf9-4205-a959-b607335fbb76.png)
![image](https://user-images.githubusercontent.com/52526629/126079454-805e31c3-3840-433e-b268-f8f32bddee8a.png)

**Desktop (please complete the following information):**
 - Windows 10 (version 20H2)
 - System type (64 bit)
 - Version (2.3.4)

**F1TV account**
- Subscription type (Pro)
- Country (Ireland)
- Using VPN or proxy? (Yes, VPN connecting to Canada)

**Additional context**
Seemed to work okay with other driver on boards, but didn't with Ricciardo's

**Comment by robvdpol** [comment] 2021-07-19 09:39
@SuRGeoNix the famous thread abort is back :)

**Comment by SuRGeoNix** [comment] 2021-07-19 09:50
@robvdpol That might be fixed with the new version. I will have another update at the next days (with recording) so it would be nice if i can include this fix as well. You might need to reproduce and debug it.  So it happens when you just pause multiple players?

**Comment by anarchomushroom** [comment] 2021-07-19 09:57
It also seemed to happen when I tried to sync all the players as well.

**Comment by SuRGeoNix** [comment] 2021-07-19 10:12
@robvdpol It's possible the you need a lock between Pause/Play (If that's the one let me know so I will added on the backend). Meanwhile, I will to try to reproduce it. (What does flyleaf do on sync all?)

**Comment by robvdpol** [comment] 2021-07-19 10:27
@SuRGeoNix The sync-button simply performs a Seek() on all open players, using the time of the active player.

**Comment by SuRGeoNix** [comment] 2021-07-19 10:35
@robvdpol It seems that you would had this issue always if it is on pause and seek. So probably the problem is that you send multiple pause/play/seek at the same player async you should lock those. Let me know if you were able to reproduce it.

**Comment by robvdpol** [comment] 2021-07-30 10:08
Possibly fixed in version 2.3.5. Please re-open if issue persists.

**Closed by robvdpol** 2021-07-30 10:08 UTC
Labels: bug
