### ISSUE TITLE
[BUG] Live session not showing in Live Now section of the app

### ISSUE THREAD

**Issue by demichel93** [robvdpol/RaceControl#171] opened 2021-06-26 11:38 UTC
**Describe the bug**
Live session not present/showing in "Live Now" section of the app. It is showing in Events->Session though. I've checked my Pi-Hole query logs for a blocked traffic but nothing present and changed for that matter since last time the feature worked which is last race weekend at France.

**To Reproduce**
Pretty self explenatory, start the app either before a live session or during a live session.

**Expected behavior**
A visible text showing a Live session.

**Screenshots**
Here's a screenshot made with pretty much all the info in picture form. Screenshot made with a VISIBLE live session on F1TV web page and in "Events->Session"
https://imgur.com/a/lED5OSa
Here are the log file output if needed: https://pastebin.com/871EXa3h

**Desktop:**
 - Windows 10 21H1, 64-bit
 - Race Control 2.3.3, installed via Microsoft Store, "Disable live session notification" option DISABLED/not ticked. I logged out and logged back in, resetted the app in Application panel in Windows. No change. Uninstalled the MS Store version and installed a MSI version, no change.

**F1TV account**
- F1 TV Pro subscription, Poland

**Comment by robvdpol** [comment] 2021-06-26 12:48
Duplicate of #167 and #168, and already fixed for next release. I'll leave this one open for now so people won't report it again.

**Closed** 2021-11-01 10:04 UTC
Labels: bug, duplicate
