### ISSUE TITLE
[BUG] Direct3D error

### ISSUE THREAD

**Issue by jdschuitemaker** [robvdpol/RaceControl#122] opened 2021-05-07 13:25 UTC
**Describe the bug**
When trying to watch a stream through the Watch button I see an error message: 
Object reference not set to an object

I click ok, then there is another message: 
HRESULT: [0x887A0001], Module [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: De toepassing heeft een ongeldige aanroep of de status van een object is onjuist. 
Schakel de D3D-foutopsporingslaag aan om details te zien via foutopsporingsberichten

**To Reproduce**
1. Start the application
2. Click 2021 Spanish GP Practice 2
3. Press button 'Watch' next to 'World feed'

**Expected behavior**
The stream should be displayed in a separate window

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Windows edition and version: Windows 10
 - System type (32 or 64 bit): 64 bit
 - Version (see title bar): 2.2.0

**F1TV account**
- Subscription type (none, Access, Pro): Pro
- Country: Netherlands
- Using VPN or proxy? No

**Additional context**

**Comment by SuRGeoNix** [comment] 2021-05-07 13:53
@jdschuitemaker Can you run 'dxdiag' command on your windows and send us System & Display tabs screenshots or Save all in .txt. It looks like a DirectX compatibility issue. If you were able to run the internal player with any other way successfully let me know.

**Comment by jdschuitemaker** [comment] 2021-05-07 14:30
I installed from the Windows Store. I seem not to have the privilege to copy the file from the zip-file to the race control folder. I have tried taking ownership of the folder, but still no luck.

**Comment by SuRGeoNix** [comment] 2021-05-07 14:57
@jdschuitemaker I have created a new draft version of a stand-alone Flyleaf player which is available [here](https://github.com/SuRGeoNix/Flyleaf/releases/download/v3.1.8/Flyleaf_v3.1.8.7z)

It would be nice if you could tested to ensure that this is actually working, try any video or hls url to ensure that is playing (eg. this one https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8 )

**Comment by jdschuitemaker** [comment] 2021-05-07 15:36
@SuRGeoNix , I extracted the file in a temporary location and downloaded the m3u8 file. Then I opened in the player, but it doesn't seem to play anything. No error message, just a white screen. I also downloaded one of the m3u8's that I found in your URL, but they don't play either.

Am I doing something wrong?

**Comment by jdschuitemaker** [comment] 2021-05-07 15:41
It is white

![image](https://user-images.githubusercontent.com/2353413/117474610-623d4780-af5b-11eb-8ae3-8a30e4ae1a6e.png)

**Comment by SuRGeoNix** [comment] 2021-05-07 15:44
It seems like a partial fix. Was it black when you initially open it? I will need your 'dxdiag' details that I asked you at the beginning

**Comment by jdschuitemaker** [comment] 2021-05-07 15:49
It is already white when I open it. 

Sorry, missed the question about dxdiag screenshots. Here they are

![image](https://user-images.githubusercontent.com/2353413/117475612-8fd6c080-af5c-11eb-835c-20439df686b7.png)

![image](https://user-images.githubusercontent.com/2353413/117475624-95340b00-af5c-11eb-8b19-ad824eb1010e.png)

**Comment by jdschuitemaker** [comment] 2021-05-07 16:02
I am a noob with this, but it says DirectX 12 and I see that it is the latest version. Or should it be DirectX12 Ultimate? Maybe update to Windows 10 version 20H2 will help?

**Comment by SuRGeoNix** [comment] 2021-05-07 16:21
You might also check updating your GPU drivers. I will give another try as well, but I've already tested on Win7/Win8 with features 10 and it is working.

**Comment by SuRGeoNix** [comment] 2021-05-14 08:20
@jdschuitemaker Any news on this one? Wasn't able to reproduce this. If that's a rare case we might close it for now? (Probably an old hardware issue)

**Closed** 2021-05-14 10:07 UTC
Labels: bug
