### ISSUE TITLE
Live session not showing in (Live Now)

### ISSUE THREAD

**Issue by Sonaclov** [robvdpol/RaceControl#168] opened 2021-06-26 10:03 UTC
Using the latest version
![image](https://user-images.githubusercontent.com/34481118/123509649-f5028480-d676-11eb-94df-68fcab2d8773.png)

**Comment by n4ppy** [comment] 2021-06-26 10:09
Same here (NL) f1tv in the browser works

**Comment by robvdpol** [comment] 2021-06-26 10:11
Duplicate of #167

**Closed by robvdpol** 2021-06-26 10:11 UTC
Labels: duplicate
